import json
import scipy.stats as ss
import os

cwd = os.getcwd()
data_dir = os.path.join(cwd, "result", "CIFAR100_15625", "vote_res")
input_file_path = os.path.join(data_dir, "201_15625_c100_128_unionBest.json")
otput_file_path = os.path.join(data_dir, "201_15625_c100_128_unionBest_with_vote.json")

with open(input_file_path,'r') as readfile:
    data_no_bn = json.load(readfile)


# update single metrics's score into rank
def update_score_to_rank(data, algName):
    archIds = []
    res = []
    for archId, info in data.items():
        res.append(float(info["scores"][algName]["score"]))
        archIds.append(archId)
    ranked_res = ss.rankdata(res)

    # update origin dict
    for archId, info in data.items():
        info["scores"][algName]["score"] = str(int(ranked_res[archIds.index(archId)]))


# add score => vote score
def add_metrics_score(info, combs):
    res = 0
    for algName in combs:
        res += int(info["scores"][algName]["score"])

    return str(res)

# add score => vote time
def add_metrics_time(info, combs):
    res = 0.0
    for algName in combs:
        res += float(info["scores"][algName]["time_usage"])

    return str(res)


all_ss = [
    "grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace",
    "ntk_trace_approx", "fisher", "grasp", "snip", "synflow"]

for metrics in all_ss:
    update_score_to_rank(data_no_bn, metrics)

all_keys = data_no_bn.keys()
print(len(all_keys))

total_vote_combination = [["grad_norm", "grad_plain", ], ["grad_norm", "nas_wot", ], ["grad_plain", "nas_wot", ],
                          ["grad_norm", "ntk_cond_num", ], ["grad_plain", "ntk_cond_num", ],
                          ["nas_wot", "ntk_cond_num", ], ["grad_norm", "ntk_trace", ], ["grad_plain", "ntk_trace", ],
                          ["nas_wot", "ntk_trace", ], ["ntk_cond_num", "ntk_trace", ],
                          ["grad_norm", "ntk_trace_approx", ], ["grad_plain", "ntk_trace_approx", ],
                          ["nas_wot", "ntk_trace_approx", ], ["ntk_cond_num", "ntk_trace_approx", ],
                          ["ntk_trace", "ntk_trace_approx", ], ["grad_norm", "fisher", ], ["grad_plain", "fisher", ],
                          ["nas_wot", "fisher", ], ["ntk_cond_num", "fisher", ], ["ntk_trace", "fisher", ],
                          ["ntk_trace_approx", "fisher", ], ["grad_norm", "grasp", ], ["grad_plain", "grasp", ],
                          ["nas_wot", "grasp", ], ["ntk_cond_num", "grasp", ], ["ntk_trace", "grasp", ],
                          ["ntk_trace_approx", "grasp", ], ["fisher", "grasp", ], ["grad_norm", "snip", ],
                          ["grad_plain", "snip", ], ["nas_wot", "snip", ], ["ntk_cond_num", "snip", ],
                          ["ntk_trace", "snip", ], ["ntk_trace_approx", "snip", ], ["fisher", "snip", ],
                          ["grasp", "snip", ], ["grad_norm", "synflow", ], ["grad_plain", "synflow", ],
                          ["nas_wot", "synflow", ], ["ntk_cond_num", "synflow", ], ["ntk_trace", "synflow", ],
                          ["ntk_trace_approx", "synflow", ], ["fisher", "synflow", ], ["grasp", "synflow", ],
                          ["snip", "synflow", ], ["grad_norm", "grad_plain", "nas_wot", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", ], ["grad_norm", "nas_wot", "ntk_cond_num", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", ], ["grad_norm", "grad_plain", "ntk_trace", ],
                          ["grad_norm", "nas_wot", "ntk_trace", ], ["grad_plain", "nas_wot", "ntk_trace", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", ], ["grad_plain", "ntk_cond_num", "ntk_trace", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", ], ["grad_norm", "grad_plain", "ntk_trace_approx", ],
                          ["grad_norm", "nas_wot", "ntk_trace_approx", ],
                          ["grad_plain", "nas_wot", "ntk_trace_approx", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace_approx", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace_approx", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace_approx", ],
                          ["grad_norm", "ntk_trace", "ntk_trace_approx", ],
                          ["grad_plain", "ntk_trace", "ntk_trace_approx", ],
                          ["nas_wot", "ntk_trace", "ntk_trace_approx", ],
                          ["ntk_cond_num", "ntk_trace", "ntk_trace_approx", ], ["grad_norm", "grad_plain", "fisher", ],
                          ["grad_norm", "nas_wot", "fisher", ], ["grad_plain", "nas_wot", "fisher", ],
                          ["grad_norm", "ntk_cond_num", "fisher", ], ["grad_plain", "ntk_cond_num", "fisher", ],
                          ["nas_wot", "ntk_cond_num", "fisher", ], ["grad_norm", "ntk_trace", "fisher", ],
                          ["grad_plain", "ntk_trace", "fisher", ], ["nas_wot", "ntk_trace", "fisher", ],
                          ["ntk_cond_num", "ntk_trace", "fisher", ], ["grad_norm", "ntk_trace_approx", "fisher", ],
                          ["grad_plain", "ntk_trace_approx", "fisher", ], ["nas_wot", "ntk_trace_approx", "fisher", ],
                          ["ntk_cond_num", "ntk_trace_approx", "fisher", ],
                          ["ntk_trace", "ntk_trace_approx", "fisher", ], ["grad_norm", "grad_plain", "grasp", ],
                          ["grad_norm", "nas_wot", "grasp", ], ["grad_plain", "nas_wot", "grasp", ],
                          ["grad_norm", "ntk_cond_num", "grasp", ], ["grad_plain", "ntk_cond_num", "grasp", ],
                          ["nas_wot", "ntk_cond_num", "grasp", ], ["grad_norm", "ntk_trace", "grasp", ],
                          ["grad_plain", "ntk_trace", "grasp", ], ["nas_wot", "ntk_trace", "grasp", ],
                          ["ntk_cond_num", "ntk_trace", "grasp", ], ["grad_norm", "ntk_trace_approx", "grasp", ],
                          ["grad_plain", "ntk_trace_approx", "grasp", ], ["nas_wot", "ntk_trace_approx", "grasp", ],
                          ["ntk_cond_num", "ntk_trace_approx", "grasp", ], ["ntk_trace", "ntk_trace_approx", "grasp", ],
                          ["grad_norm", "fisher", "grasp", ], ["grad_plain", "fisher", "grasp", ],
                          ["nas_wot", "fisher", "grasp", ], ["ntk_cond_num", "fisher", "grasp", ],
                          ["ntk_trace", "fisher", "grasp", ], ["ntk_trace_approx", "fisher", "grasp", ],
                          ["grad_norm", "grad_plain", "snip", ], ["grad_norm", "nas_wot", "snip", ],
                          ["grad_plain", "nas_wot", "snip", ], ["grad_norm", "ntk_cond_num", "snip", ],
                          ["grad_plain", "ntk_cond_num", "snip", ], ["nas_wot", "ntk_cond_num", "snip", ],
                          ["grad_norm", "ntk_trace", "snip", ], ["grad_plain", "ntk_trace", "snip", ],
                          ["nas_wot", "ntk_trace", "snip", ], ["ntk_cond_num", "ntk_trace", "snip", ],
                          ["grad_norm", "ntk_trace_approx", "snip", ], ["grad_plain", "ntk_trace_approx", "snip", ],
                          ["nas_wot", "ntk_trace_approx", "snip", ], ["ntk_cond_num", "ntk_trace_approx", "snip", ],
                          ["ntk_trace", "ntk_trace_approx", "snip", ], ["grad_norm", "fisher", "snip", ],
                          ["grad_plain", "fisher", "snip", ], ["nas_wot", "fisher", "snip", ],
                          ["ntk_cond_num", "fisher", "snip", ], ["ntk_trace", "fisher", "snip", ],
                          ["ntk_trace_approx", "fisher", "snip", ], ["grad_norm", "grasp", "snip", ],
                          ["grad_plain", "grasp", "snip", ], ["nas_wot", "grasp", "snip", ],
                          ["ntk_cond_num", "grasp", "snip", ], ["ntk_trace", "grasp", "snip", ],
                          ["ntk_trace_approx", "grasp", "snip", ], ["fisher", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "synflow", ], ["grad_norm", "nas_wot", "synflow", ],
                          ["grad_plain", "nas_wot", "synflow", ], ["grad_norm", "ntk_cond_num", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "synflow", ], ["nas_wot", "ntk_cond_num", "synflow", ],
                          ["grad_norm", "ntk_trace", "synflow", ], ["grad_plain", "ntk_trace", "synflow", ],
                          ["nas_wot", "ntk_trace", "synflow", ], ["ntk_cond_num", "ntk_trace", "synflow", ],
                          ["grad_norm", "ntk_trace_approx", "synflow", ],
                          ["grad_plain", "ntk_trace_approx", "synflow", ], ["nas_wot", "ntk_trace_approx", "synflow", ],
                          ["ntk_cond_num", "ntk_trace_approx", "synflow", ],
                          ["ntk_trace", "ntk_trace_approx", "synflow", ], ["grad_norm", "fisher", "synflow", ],
                          ["grad_plain", "fisher", "synflow", ], ["nas_wot", "fisher", "synflow", ],
                          ["ntk_cond_num", "fisher", "synflow", ], ["ntk_trace", "fisher", "synflow", ],
                          ["ntk_trace_approx", "fisher", "synflow", ], ["grad_norm", "grasp", "synflow", ],
                          ["grad_plain", "grasp", "synflow", ], ["nas_wot", "grasp", "synflow", ],
                          ["ntk_cond_num", "grasp", "synflow", ], ["ntk_trace", "grasp", "synflow", ],
                          ["ntk_trace_approx", "grasp", "synflow", ], ["fisher", "grasp", "synflow", ],
                          ["grad_norm", "snip", "synflow", ], ["grad_plain", "snip", "synflow", ],
                          ["nas_wot", "snip", "synflow", ], ["ntk_cond_num", "snip", "synflow", ],
                          ["ntk_trace", "snip", "synflow", ], ["ntk_trace_approx", "snip", "synflow", ],
                          ["fisher", "snip", "synflow", ], ["grasp", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace_approx", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace_approx", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace_approx", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "ntk_trace_approx", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "ntk_trace_approx", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", ],
                          ["grad_norm", "grad_plain", "nas_wot", "fisher", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "fisher", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "fisher", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "fisher", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "fisher", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "fisher", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "fisher", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "fisher", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "fisher", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "fisher", ],
                          ["grad_norm", "grad_plain", "ntk_trace_approx", "fisher", ],
                          ["grad_norm", "nas_wot", "ntk_trace_approx", "fisher", ],
                          ["grad_plain", "nas_wot", "ntk_trace_approx", "fisher", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace_approx", "fisher", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace_approx", "fisher", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", ],
                          ["grad_norm", "ntk_trace", "ntk_trace_approx", "fisher", ],
                          ["grad_plain", "ntk_trace", "ntk_trace_approx", "fisher", ],
                          ["nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", ],
                          ["ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", ],
                          ["grad_norm", "grad_plain", "nas_wot", "grasp", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "grasp", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "grasp", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "grasp", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "grasp", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "grasp", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "grasp", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "grasp", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "grasp", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "grasp", ],
                          ["grad_norm", "grad_plain", "ntk_trace_approx", "grasp", ],
                          ["grad_norm", "nas_wot", "ntk_trace_approx", "grasp", ],
                          ["grad_plain", "nas_wot", "ntk_trace_approx", "grasp", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace_approx", "grasp", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace_approx", "grasp", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace_approx", "grasp", ],
                          ["grad_norm", "ntk_trace", "ntk_trace_approx", "grasp", ],
                          ["grad_plain", "ntk_trace", "ntk_trace_approx", "grasp", ],
                          ["nas_wot", "ntk_trace", "ntk_trace_approx", "grasp", ],
                          ["ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", ],
                          ["grad_norm", "grad_plain", "fisher", "grasp", ],
                          ["grad_norm", "nas_wot", "fisher", "grasp", ], ["grad_plain", "nas_wot", "fisher", "grasp", ],
                          ["grad_norm", "ntk_cond_num", "fisher", "grasp", ],
                          ["grad_plain", "ntk_cond_num", "fisher", "grasp", ],
                          ["nas_wot", "ntk_cond_num", "fisher", "grasp", ],
                          ["grad_norm", "ntk_trace", "fisher", "grasp", ],
                          ["grad_plain", "ntk_trace", "fisher", "grasp", ],
                          ["nas_wot", "ntk_trace", "fisher", "grasp", ],
                          ["ntk_cond_num", "ntk_trace", "fisher", "grasp", ],
                          ["grad_norm", "ntk_trace_approx", "fisher", "grasp", ],
                          ["grad_plain", "ntk_trace_approx", "fisher", "grasp", ],
                          ["nas_wot", "ntk_trace_approx", "fisher", "grasp", ],
                          ["ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", ],
                          ["ntk_trace", "ntk_trace_approx", "fisher", "grasp", ],
                          ["grad_norm", "grad_plain", "nas_wot", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "snip", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "snip", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "snip", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_trace_approx", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_trace_approx", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_trace_approx", "snip", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace_approx", "snip", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace_approx", "snip", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace_approx", "snip", ],
                          ["grad_norm", "ntk_trace", "ntk_trace_approx", "snip", ],
                          ["grad_plain", "ntk_trace", "ntk_trace_approx", "snip", ],
                          ["nas_wot", "ntk_trace", "ntk_trace_approx", "snip", ],
                          ["ntk_cond_num", "ntk_trace", "ntk_trace_approx", "snip", ],
                          ["grad_norm", "grad_plain", "fisher", "snip", ], ["grad_norm", "nas_wot", "fisher", "snip", ],
                          ["grad_plain", "nas_wot", "fisher", "snip", ],
                          ["grad_norm", "ntk_cond_num", "fisher", "snip", ],
                          ["grad_plain", "ntk_cond_num", "fisher", "snip", ],
                          ["nas_wot", "ntk_cond_num", "fisher", "snip", ],
                          ["grad_norm", "ntk_trace", "fisher", "snip", ],
                          ["grad_plain", "ntk_trace", "fisher", "snip", ], ["nas_wot", "ntk_trace", "fisher", "snip", ],
                          ["ntk_cond_num", "ntk_trace", "fisher", "snip", ],
                          ["grad_norm", "ntk_trace_approx", "fisher", "snip", ],
                          ["grad_plain", "ntk_trace_approx", "fisher", "snip", ],
                          ["nas_wot", "ntk_trace_approx", "fisher", "snip", ],
                          ["ntk_cond_num", "ntk_trace_approx", "fisher", "snip", ],
                          ["ntk_trace", "ntk_trace_approx", "fisher", "snip", ],
                          ["grad_norm", "grad_plain", "grasp", "snip", ], ["grad_norm", "nas_wot", "grasp", "snip", ],
                          ["grad_plain", "nas_wot", "grasp", "snip", ],
                          ["grad_norm", "ntk_cond_num", "grasp", "snip", ],
                          ["grad_plain", "ntk_cond_num", "grasp", "snip", ],
                          ["nas_wot", "ntk_cond_num", "grasp", "snip", ], ["grad_norm", "ntk_trace", "grasp", "snip", ],
                          ["grad_plain", "ntk_trace", "grasp", "snip", ], ["nas_wot", "ntk_trace", "grasp", "snip", ],
                          ["ntk_cond_num", "ntk_trace", "grasp", "snip", ],
                          ["grad_norm", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_plain", "ntk_trace_approx", "grasp", "snip", ],
                          ["nas_wot", "ntk_trace_approx", "grasp", "snip", ],
                          ["ntk_cond_num", "ntk_trace_approx", "grasp", "snip", ],
                          ["ntk_trace", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_norm", "fisher", "grasp", "snip", ], ["grad_plain", "fisher", "grasp", "snip", ],
                          ["nas_wot", "fisher", "grasp", "snip", ], ["ntk_cond_num", "fisher", "grasp", "snip", ],
                          ["ntk_trace", "fisher", "grasp", "snip", ], ["ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace_approx", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace_approx", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace_approx", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace_approx", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace_approx", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace_approx", "synflow", ],
                          ["grad_norm", "ntk_trace", "ntk_trace_approx", "synflow", ],
                          ["grad_plain", "ntk_trace", "ntk_trace_approx", "synflow", ],
                          ["nas_wot", "ntk_trace", "ntk_trace_approx", "synflow", ],
                          ["ntk_cond_num", "ntk_trace", "ntk_trace_approx", "synflow", ],
                          ["grad_norm", "grad_plain", "fisher", "synflow", ],
                          ["grad_norm", "nas_wot", "fisher", "synflow", ],
                          ["grad_plain", "nas_wot", "fisher", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "fisher", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "fisher", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "fisher", "synflow", ],
                          ["grad_norm", "ntk_trace", "fisher", "synflow", ],
                          ["grad_plain", "ntk_trace", "fisher", "synflow", ],
                          ["nas_wot", "ntk_trace", "fisher", "synflow", ],
                          ["ntk_cond_num", "ntk_trace", "fisher", "synflow", ],
                          ["grad_norm", "ntk_trace_approx", "fisher", "synflow", ],
                          ["grad_plain", "ntk_trace_approx", "fisher", "synflow", ],
                          ["nas_wot", "ntk_trace_approx", "fisher", "synflow", ],
                          ["ntk_cond_num", "ntk_trace_approx", "fisher", "synflow", ],
                          ["ntk_trace", "ntk_trace_approx", "fisher", "synflow", ],
                          ["grad_norm", "grad_plain", "grasp", "synflow", ],
                          ["grad_norm", "nas_wot", "grasp", "synflow", ],
                          ["grad_plain", "nas_wot", "grasp", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "grasp", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "grasp", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "grasp", "synflow", ],
                          ["grad_norm", "ntk_trace", "grasp", "synflow", ],
                          ["grad_plain", "ntk_trace", "grasp", "synflow", ],
                          ["nas_wot", "ntk_trace", "grasp", "synflow", ],
                          ["ntk_cond_num", "ntk_trace", "grasp", "synflow", ],
                          ["grad_norm", "ntk_trace_approx", "grasp", "synflow", ],
                          ["grad_plain", "ntk_trace_approx", "grasp", "synflow", ],
                          ["nas_wot", "ntk_trace_approx", "grasp", "synflow", ],
                          ["ntk_cond_num", "ntk_trace_approx", "grasp", "synflow", ],
                          ["ntk_trace", "ntk_trace_approx", "grasp", "synflow", ],
                          ["grad_norm", "fisher", "grasp", "synflow", ], ["grad_plain", "fisher", "grasp", "synflow", ],
                          ["nas_wot", "fisher", "grasp", "synflow", ], ["ntk_cond_num", "fisher", "grasp", "synflow", ],
                          ["ntk_trace", "fisher", "grasp", "synflow", ],
                          ["ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "snip", "synflow", ], ["grad_plain", "nas_wot", "snip", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "snip", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "snip", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "snip", "synflow", ],
                          ["grad_norm", "ntk_trace", "snip", "synflow", ],
                          ["grad_plain", "ntk_trace", "snip", "synflow", ],
                          ["nas_wot", "ntk_trace", "snip", "synflow", ],
                          ["ntk_cond_num", "ntk_trace", "snip", "synflow", ],
                          ["grad_norm", "ntk_trace_approx", "snip", "synflow", ],
                          ["grad_plain", "ntk_trace_approx", "snip", "synflow", ],
                          ["nas_wot", "ntk_trace_approx", "snip", "synflow", ],
                          ["ntk_cond_num", "ntk_trace_approx", "snip", "synflow", ],
                          ["ntk_trace", "ntk_trace_approx", "snip", "synflow", ],
                          ["grad_norm", "fisher", "snip", "synflow", ], ["grad_plain", "fisher", "snip", "synflow", ],
                          ["nas_wot", "fisher", "snip", "synflow", ], ["ntk_cond_num", "fisher", "snip", "synflow", ],
                          ["ntk_trace", "fisher", "snip", "synflow", ],
                          ["ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["grad_norm", "grasp", "snip", "synflow", ], ["grad_plain", "grasp", "snip", "synflow", ],
                          ["nas_wot", "grasp", "snip", "synflow", ], ["ntk_cond_num", "grasp", "snip", "synflow", ],
                          ["ntk_trace", "grasp", "snip", "synflow", ],
                          ["ntk_trace_approx", "grasp", "snip", "synflow", ], ["fisher", "grasp", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "fisher", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "fisher", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "fisher", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace_approx", "fisher", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace_approx", "fisher", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "ntk_trace_approx", "fisher", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "grasp", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "grasp", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "grasp", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "grasp", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "grasp", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace_approx", "grasp", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace_approx", "grasp", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "grasp", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "grasp", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "ntk_trace_approx", "grasp", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "ntk_trace_approx", "grasp", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "grasp", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", ],
                          ["grad_norm", "grad_plain", "nas_wot", "fisher", "grasp", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "fisher", "grasp", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "fisher", "grasp", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "fisher", "grasp", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "fisher", "grasp", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "fisher", "grasp", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "fisher", "grasp", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "fisher", "grasp", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "fisher", "grasp", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "grasp", ],
                          ["grad_norm", "grad_plain", "ntk_trace_approx", "fisher", "grasp", ],
                          ["grad_norm", "nas_wot", "ntk_trace_approx", "fisher", "grasp", ],
                          ["grad_plain", "nas_wot", "ntk_trace_approx", "fisher", "grasp", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", ],
                          ["grad_norm", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", ],
                          ["grad_plain", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", ],
                          ["nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", ],
                          ["ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace_approx", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace_approx", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "ntk_trace_approx", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "ntk_trace_approx", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "snip", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "snip", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "snip", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "fisher", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "fisher", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "fisher", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "fisher", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "fisher", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "fisher", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "fisher", "snip", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "fisher", "snip", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "fisher", "snip", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_trace_approx", "fisher", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_trace_approx", "fisher", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_trace_approx", "fisher", "snip", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace_approx", "fisher", "snip", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace_approx", "fisher", "snip", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "snip", ],
                          ["grad_norm", "ntk_trace", "ntk_trace_approx", "fisher", "snip", ],
                          ["grad_plain", "ntk_trace", "ntk_trace_approx", "fisher", "snip", ],
                          ["nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "snip", ],
                          ["ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "grasp", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "grasp", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "grasp", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "grasp", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "grasp", "snip", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "grasp", "snip", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "grasp", "snip", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace_approx", "grasp", "snip", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_norm", "ntk_trace", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_plain", "ntk_trace", "ntk_trace_approx", "grasp", "snip", ],
                          ["nas_wot", "ntk_trace", "ntk_trace_approx", "grasp", "snip", ],
                          ["ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "fisher", "grasp", "snip", ],
                          ["grad_norm", "nas_wot", "fisher", "grasp", "snip", ],
                          ["grad_plain", "nas_wot", "fisher", "grasp", "snip", ],
                          ["grad_norm", "ntk_cond_num", "fisher", "grasp", "snip", ],
                          ["grad_plain", "ntk_cond_num", "fisher", "grasp", "snip", ],
                          ["nas_wot", "ntk_cond_num", "fisher", "grasp", "snip", ],
                          ["grad_norm", "ntk_trace", "fisher", "grasp", "snip", ],
                          ["grad_plain", "ntk_trace", "fisher", "grasp", "snip", ],
                          ["nas_wot", "ntk_trace", "fisher", "grasp", "snip", ],
                          ["ntk_cond_num", "ntk_trace", "fisher", "grasp", "snip", ],
                          ["grad_norm", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["grad_plain", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["nas_wot", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace_approx", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace_approx", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "ntk_trace_approx", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "ntk_trace_approx", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "fisher", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "fisher", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "fisher", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "fisher", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "fisher", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "fisher", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "fisher", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "fisher", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "fisher", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace_approx", "fisher", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace_approx", "fisher", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace_approx", "fisher", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace_approx", "fisher", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace_approx", "fisher", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "synflow", ],
                          ["grad_norm", "ntk_trace", "ntk_trace_approx", "fisher", "synflow", ],
                          ["grad_plain", "ntk_trace", "ntk_trace_approx", "fisher", "synflow", ],
                          ["nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "synflow", ],
                          ["ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "grasp", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "grasp", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "grasp", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "grasp", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "grasp", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "grasp", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "grasp", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace_approx", "grasp", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace_approx", "grasp", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace_approx", "grasp", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace_approx", "grasp", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace_approx", "grasp", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace_approx", "grasp", "synflow", ],
                          ["grad_norm", "ntk_trace", "ntk_trace_approx", "grasp", "synflow", ],
                          ["grad_plain", "ntk_trace", "ntk_trace_approx", "grasp", "synflow", ],
                          ["nas_wot", "ntk_trace", "ntk_trace_approx", "grasp", "synflow", ],
                          ["ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "nas_wot", "fisher", "grasp", "synflow", ],
                          ["grad_plain", "nas_wot", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "fisher", "grasp", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "fisher", "grasp", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "ntk_trace", "fisher", "grasp", "synflow", ],
                          ["grad_plain", "ntk_trace", "fisher", "grasp", "synflow", ],
                          ["nas_wot", "ntk_trace", "fisher", "grasp", "synflow", ],
                          ["ntk_cond_num", "ntk_trace", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["grad_plain", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["nas_wot", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["ntk_trace", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "snip", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "snip", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "snip", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace_approx", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace_approx", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace_approx", "snip", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace_approx", "snip", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace_approx", "snip", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace_approx", "snip", "synflow", ],
                          ["grad_norm", "ntk_trace", "ntk_trace_approx", "snip", "synflow", ],
                          ["grad_plain", "ntk_trace", "ntk_trace_approx", "snip", "synflow", ],
                          ["nas_wot", "ntk_trace", "ntk_trace_approx", "snip", "synflow", ],
                          ["ntk_cond_num", "ntk_trace", "ntk_trace_approx", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "fisher", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "fisher", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "fisher", "snip", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "fisher", "snip", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "fisher", "snip", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "fisher", "snip", "synflow", ],
                          ["grad_norm", "ntk_trace", "fisher", "snip", "synflow", ],
                          ["grad_plain", "ntk_trace", "fisher", "snip", "synflow", ],
                          ["nas_wot", "ntk_trace", "fisher", "snip", "synflow", ],
                          ["ntk_cond_num", "ntk_trace", "fisher", "snip", "synflow", ],
                          ["grad_norm", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["grad_plain", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["nas_wot", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["ntk_cond_num", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["ntk_trace", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "grasp", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "grasp", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "grasp", "snip", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "grasp", "snip", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "grasp", "snip", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "grasp", "snip", "synflow", ],
                          ["grad_norm", "ntk_trace", "grasp", "snip", "synflow", ],
                          ["grad_plain", "ntk_trace", "grasp", "snip", "synflow", ],
                          ["nas_wot", "ntk_trace", "grasp", "snip", "synflow", ],
                          ["ntk_cond_num", "ntk_trace", "grasp", "snip", "synflow", ],
                          ["grad_norm", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["grad_plain", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["nas_wot", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["ntk_cond_num", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["ntk_trace", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["grad_norm", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_plain", "fisher", "grasp", "snip", "synflow", ],
                          ["nas_wot", "fisher", "grasp", "snip", "synflow", ],
                          ["ntk_cond_num", "fisher", "grasp", "snip", "synflow", ],
                          ["ntk_trace", "fisher", "grasp", "snip", "synflow", ],
                          ["ntk_trace_approx", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "grasp", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "grasp", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "grasp", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "fisher", "grasp", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "fisher", "grasp", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "fisher", "grasp", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "grasp", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "grasp", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace_approx", "fisher", "grasp", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "fisher", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "fisher", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "fisher", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace_approx", "fisher", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace_approx", "fisher", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "ntk_trace_approx", "fisher", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "snip", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "snip", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "snip", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "grasp", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "grasp", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", "snip", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "fisher", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "fisher", "grasp", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "fisher", "grasp", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "fisher", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "fisher", "grasp", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "fisher", "grasp", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "fisher", "grasp", "snip", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "fisher", "grasp", "snip", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "fisher", "grasp", "snip", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["grad_norm", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["grad_plain", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "fisher", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "fisher", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "fisher", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace_approx", "fisher", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace_approx", "fisher", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "ntk_trace_approx", "fisher", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "grasp", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "grasp", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace_approx", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace_approx", "grasp", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "grasp", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "ntk_trace_approx", "grasp", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "ntk_trace_approx", "grasp", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "grasp", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "fisher", "grasp", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "fisher", "grasp", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "fisher", "grasp", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "fisher", "grasp", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["grad_plain", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace_approx", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace_approx", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "ntk_trace_approx", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "ntk_trace_approx", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "snip", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "snip", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "snip", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "fisher", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "fisher", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "fisher", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "fisher", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "fisher", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "fisher", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "fisher", "snip", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "fisher", "snip", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "fisher", "snip", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["grad_norm", "ntk_trace", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["grad_plain", "ntk_trace", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "grasp", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "grasp", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "grasp", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "grasp", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "grasp", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "grasp", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "grasp", "snip", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "grasp", "snip", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "grasp", "snip", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "grasp", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["grad_norm", "ntk_trace", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["grad_plain", "ntk_trace", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["nas_wot", "ntk_trace", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "fisher", "grasp", "snip", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_norm", "ntk_trace", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_plain", "ntk_trace", "fisher", "grasp", "snip", "synflow", ],
                          ["nas_wot", "ntk_trace", "fisher", "grasp", "snip", "synflow", ],
                          ["ntk_cond_num", "ntk_trace", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_norm", "ntk_trace_approx", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_plain", "ntk_trace_approx", "fisher", "grasp", "snip", "synflow", ],
                          ["nas_wot", "ntk_trace_approx", "fisher", "grasp", "snip", "synflow", ],
                          ["ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", "snip", "synflow", ],
                          ["ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx",
                           "fisher", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx",
                           "grasp", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "grasp", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher",
                           "grasp", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher",
                           "grasp", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher",
                           "grasp", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher",
                           "grasp", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx",
                           "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher",
                           "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher",
                           "snip", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher",
                           "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp",
                           "snip", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "fisher", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "fisher", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "fisher", "grasp", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "grasp", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher",
                           "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher",
                           "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "grasp",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp",
                           "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp",
                           "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "grasp", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp",
                           "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp",
                           "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp",
                           "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "snip",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "snip",
                           "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "snip",
                           "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "snip",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "fisher", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "fisher", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "fisher", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace_approx", "fisher", "snip",
                           "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "snip",
                           "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "grasp", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "grasp", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "grasp", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "grasp", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "grasp", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "fisher", "grasp", "snip", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace_approx", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace_approx", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace_approx", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", "snip", "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_norm", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_plain", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip", "synflow", ],
                          ["nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip", "synflow", ],
                          ["ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx",
                           "fisher", "grasp", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx",
                           "fisher", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx",
                           "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "grasp",
                           "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp",
                           "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "grasp",
                           "snip", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher",
                           "grasp", "snip", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp",
                           "snip", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp",
                           "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx",
                           "fisher", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx",
                           "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "grasp",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "grasp",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher",
                           "grasp", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp",
                           "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx",
                           "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "snip",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "snip",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "snip",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "snip",
                           "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "snip",
                           "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "snip",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "grasp", "snip",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "grasp", "snip",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "grasp", "snip",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", "snip",
                           "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", "snip",
                           "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "grasp", "snip",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "fisher", "grasp", "snip",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "fisher", "grasp", "snip",
                           "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "grasp", "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "grasp", "snip",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace_approx", "fisher", "grasp", "snip",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", "snip",
                           "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", "snip",
                           "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp", "snip",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip",
                           "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip",
                           "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip",
                           "synflow", ],
                          ["grad_norm", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip",
                           "synflow", ],
                          ["grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip",
                           "synflow", ],
                          ["nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp", "snip",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx",
                           "fisher", "grasp", "snip", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx",
                           "fisher", "grasp", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx",
                           "fisher", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx",
                           "grasp", "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "fisher", "grasp", "snip",
                           "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace_approx", "fisher", "grasp",
                           "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "nas_wot", "ntk_trace", "ntk_trace_approx", "fisher", "grasp",
                           "snip", "synflow", ],
                          ["grad_norm", "grad_plain", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher",
                           "grasp", "snip", "synflow", ],
                          ["grad_norm", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp",
                           "snip", "synflow", ],
                          ["grad_plain", "nas_wot", "ntk_cond_num", "ntk_trace", "ntk_trace_approx", "fisher", "grasp",
                           "snip", "synflow", ], ]

for archId, info in data_no_bn.items():

    for comb in total_vote_combination:
        info["scores"][str(comb)] = {}
        info["scores"][str(comb)]["score"] = add_metrics_score(info, comb)
        info["scores"][str(comb)]["time_usage"] = add_metrics_time(info, comb)

with open(otput_file_path,'w') as outfile:
    outfile.write(json.dumps(data_no_bn))
