








python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:1     --batch_size=1024     --lr=0.001     --epoch=10     --iter_per_epoch=2000     --dataset=criteo     --nfeat=2100000     --nfield=39     --nemb=10     --worker_id=48     --total_workers=54     --workers=0     --log_folder=LogCriteo     --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/sampled_models_10000_models.json > output.log&
python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:1     --batch_size=1024     --lr=0.001     --epoch=10     --iter_per_epoch=2000     --dataset=criteo     --nfeat=2100000     --nfield=39     --nemb=10     --worker_id=49     --total_workers=54     --workers=0     --log_folder=LogCriteo     --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/sampled_models_10000_models.json > output.log&
python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:1     --batch_size=1024     --lr=0.001     --epoch=10     --iter_per_epoch=2000     --dataset=criteo     --nfeat=2100000     --nfield=39     --nemb=10     --worker_id=50     --total_workers=54     --workers=0     --log_folder=LogCriteo     --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/sampled_models_10000_models.json > output.log&
python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:1     --batch_size=1024     --lr=0.001     --epoch=10     --iter_per_epoch=2000     --dataset=criteo     --nfeat=2100000     --nfield=39     --nemb=10     --worker_id=51     --total_workers=54     --workers=0     --log_folder=LogCriteo     --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/sampled_models_10000_models.json > output.log&
python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:1     --batch_size=1024     --lr=0.001     --epoch=10     --iter_per_epoch=2000     --dataset=criteo     --nfeat=2100000     --nfield=39     --nemb=10     --worker_id=52     --total_workers=54     --workers=0     --log_folder=LogCriteo     --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/sampled_models_10000_models.json > output.log&
python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:1     --batch_size=1024     --lr=0.001     --epoch=10     --iter_per_epoch=2000     --dataset=criteo     --nfeat=2100000     --nfield=39     --nemb=10     --worker_id=53     --total_workers=54     --workers=0     --log_folder=LogCriteo     --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/sampled_models_10000_models.json > output.log&