




# XAI: 25 jobs
nohup python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:0     --batch_size=1024     --lr=0.001     --epoch=10     --iter_per_epoch=2000     --dataset=criteo     --nfeat=2100000     --nfield=39     --nemb=10     --worker_id=0     --total_workers=7     --workers=0     --log_folder=LogCriteo700Left     --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/all_models_criteo_left.json > output.log&
nohup python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:1     --batch_size=1024     --lr=0.001     --epoch=10     --iter_per_epoch=2000     --dataset=criteo     --nfeat=2100000     --nfield=39     --nemb=10     --worker_id=1     --total_workers=7     --workers=0     --log_folder=LogCriteo700Left     --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/all_models_criteo_left.json > output.log&
nohup python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:0     --batch_size=1024     --lr=0.001     --epoch=10     --iter_per_epoch=2000     --dataset=criteo     --nfeat=2100000     --nfield=39     --nemb=10     --worker_id=2     --total_workers=7     --workers=0     --log_folder=LogCriteo700Left     --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/all_models_criteo_left.json > output.log&
nohup python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:1     --batch_size=1024     --lr=0.001     --epoch=10     --iter_per_epoch=2000     --dataset=criteo     --nfeat=2100000     --nfield=39     --nemb=10     --worker_id=3     --total_workers=7     --workers=0     --log_folder=LogCriteo700Left     --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/all_models_criteo_left.json > output.log&
nohup python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:0     --batch_size=1024     --lr=0.001     --epoch=10     --iter_per_epoch=2000     --dataset=criteo     --nfeat=2100000     --nfield=39     --nemb=10     --worker_id=4     --total_workers=7     --workers=0     --log_folder=LogCriteo700Left     --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/all_models_criteo_left.json > output.log&
nohup python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:1     --batch_size=1024     --lr=0.001     --epoch=10     --iter_per_epoch=2000     --dataset=criteo     --nfeat=2100000     --nfield=39     --nemb=10     --worker_id=5     --total_workers=7     --workers=0     --log_folder=LogCriteo700Left     --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/all_models_criteo_left.json > output.log&
nohup python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:0     --batch_size=1024     --lr=0.001     --epoch=10     --iter_per_epoch=2000     --dataset=criteo     --nfeat=2100000     --nfield=39     --nemb=10     --worker_id=6     --total_workers=7     --workers=0     --log_folder=LogCriteo700Left     --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/all_models_criteo_left.json > output.log&

