*


nohup python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:0     --batch_size=1024     --lr=0.001     --epoch=5     --iter_per_epoch=200     --dataset=uci_diabetes     --nfeat=369     --nfield=43     --nemb=10     --worker_id=0     --total_workers=11     --workers=0     --log_folder=LogUci10K      --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/sampled_models_10000_models.json > outputuci.log&
nohup python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:1     --batch_size=1024     --lr=0.001     --epoch=5     --iter_per_epoch=200     --dataset=uci_diabetes     --nfeat=369     --nfield=43     --nemb=10     --worker_id=1     --total_workers=11     --workers=0     --log_folder=LogUci10K      --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/sampled_models_10000_models.json > outputuci.log&
nohup python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:2     --batch_size=1024     --lr=0.001     --epoch=5     --iter_per_epoch=200     --dataset=uci_diabetes     --nfeat=369     --nfield=43     --nemb=10     --worker_id=2     --total_workers=11     --workers=0     --log_folder=LogUci10K      --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/sampled_models_10000_models.json > outputuci.log&
nohup python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:3     --batch_size=1024     --lr=0.001     --epoch=5     --iter_per_epoch=200     --dataset=uci_diabetes     --nfeat=369     --nfield=43     --nemb=10     --worker_id=3     --total_workers=11     --workers=0     --log_folder=LogUci10K      --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/sampled_models_10000_models.json > outputuci.log&

nohup python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:4     --batch_size=1024     --lr=0.001     --epoch=5     --iter_per_epoch=200     --dataset=uci_diabetes     --nfeat=369     --nfield=43     --nemb=10     --worker_id=4     --total_workers=11     --workers=0     --log_folder=LogUci10K      --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/sampled_models_10000_models.json > outputuci.log&
nohup python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:5     --batch_size=1024     --lr=0.001     --epoch=5     --iter_per_epoch=200     --dataset=uci_diabetes     --nfeat=369     --nfield=43     --nemb=10     --worker_id=5     --total_workers=11     --workers=0     --log_folder=LogUci10K      --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/sampled_models_10000_models.json > outputuci.log&
nohup python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:0     --batch_size=1024     --lr=0.001     --epoch=5     --iter_per_epoch=200     --dataset=uci_diabetes     --nfeat=369     --nfield=43     --nemb=10     --worker_id=6     --total_workers=11     --workers=0     --log_folder=LogUci10K      --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/sampled_models_10000_models.json > outputuci.log&
nohup python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:1     --batch_size=1024     --lr=0.001     --epoch=5     --iter_per_epoch=200     --dataset=uci_diabetes     --nfeat=369     --nfield=43     --nemb=10     --worker_id=7     --total_workers=11     --workers=0     --log_folder=LogUci10K      --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/sampled_models_10000_models.json > outputuci.log&

nohup python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:2     --batch_size=1024     --lr=0.001     --epoch=5     --iter_per_epoch=200     --dataset=uci_diabetes     --nfeat=369     --nfield=43     --nemb=10     --worker_id=8     --total_workers=11     --workers=0     --log_folder=LogUci10K      --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/sampled_models_10000_models.json > outputuci.log&
nohup python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:3     --batch_size=1024     --lr=0.001     --epoch=5     --iter_per_epoch=200     --dataset=uci_diabetes     --nfeat=369     --nfield=43     --nemb=10     --worker_id=9     --total_workers=11     --workers=0     --log_folder=LogUci10K      --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/sampled_models_10000_models.json > outputuci.log&
nohup python exps/main_sigmod/ground_truth/2.seq_train_online.py      --log_name=baseline_train_based     --search_space=mlp_sp     --num_layers=4     --hidden_choice_len=10     --base_dir=../firmest_data/     --num_labels=1     --device=cuda:4     --batch_size=1024     --lr=0.001     --epoch=5     --iter_per_epoch=200     --dataset=uci_diabetes     --nfeat=369     --nfield=43     --nemb=10     --worker_id=10     --total_workers=11     --workers=0     --log_folder=LogUci10K      --total_models_per_worker=-1     --pre_partitioned_file=./exps/main_sigmod/ground_truth/sampled_models_10000_models.json > outputuci.log&
